name: Merge Rama Principal
on:
  push:
    branches: [ develop ]
jobs:
  job-1:
    name: Validar Commit
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    runs-on: ubuntu-latest
    steps:
    - name: Validar 
      env:
        MI_VARIABLE: Hola mundo..
      run: |
        echo $MI_VARIABLE.
